name: thindek_ui
description: Flutter UI toolkit for developing thindek's mobile applications 
version: 0.4.5
homepage: https://www.thindek.com/

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_screenutil: ^5.0.0+2 #屏幕适配
  fluttertoast: ^8.0.7 #消息弹框
  cached_network_image: ^3.0.0 #网络图片缓存
  extended_text: ^7.0.0 #定制扩展文本
  badges: ^2.0.1 #Badges
  flutter_card_swipper: ^0.4.0 #页面轮播图
#  flutter_icons: ^1.1.0



#等待测试加入
#  extended_image: ^3.0.0-non-null-safety #图片处理
#  flutter_html: ^1.0.2 #HTML




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

