name: thindek_ui
description: Flutter UI toolkit for developing thindek's mobile applications 
version: 0.2.2
homepage: https://thindek.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dynamic_theme: ^1.0.1

  analyzer: ^0.39.15

  # LeanCloud 数据存储
  leancloud_storage: ^0.4.3

  # 路由管理
  auto_route: ^0.6.7

  # 屏幕适配
  flutter_screenutil: ^3.1.1

  # 网页浏览
  webview_flutter: ^0.3.22+1

  # 消息弹框
  fluttertoast: ^7.1.1

  # 滑动刷新
  flutter_easyrefresh: ^2.1.5

  # Icons
  flutter_icons: ^1.1.0

  # 网络图片缓存
  cached_network_image: ^2.0.0

  # 链接预览
  flutter_link_preview: ^1.5.6

  # 富文本
  flutter_parsed_text: ^1.2.5

  # 定制扩展文本
  extended_text: ^4.0.0

  #页面轮播图
  flutter_swiper: ^1.1.6







dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
