name: thindek_ui
description: Flutter UI toolkit for developing thindek's mobile applications 
version: 0.4.5
homepage: https://www.thindek.com/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_screenutil: ^4.0.0 #屏幕适配
  fluttertoast: ^7.1.1 #消息弹框
  cached_network_image: ^2.5.0 #网络图片缓存
  extended_text: ^4.0.0 #定制扩展文本
  flutter_swiper: ^1.1.6 #页面轮播图

#等待测试加入
#  badges: ^1.1.3 #Badges
#  extended_image: ^3.0.0-non-null-safety
#  flutter_html: ^1.0.2 #HTML
#  flutter_icons: ^1.1.0 #Icons




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

