name: thindek_ui
description: Flutter UI toolkit for developing thindek's mobile applications 
version: 0.3.3
homepage: https://thindek.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_screenutil: ^3.1.1 #屏幕适配
  fluttertoast: ^7.1.1 #消息弹框
  cached_network_image: ^2.0.0 #网络图片缓存
  extended_text: ^4.0.0 #定制扩展文本
  flutter_swiper: ^1.1.6 #页面轮播图




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

